BEGIN{
    FS=":"
    OFS=","
    print "DTSTART", "DTEND", "LOCATION", "SUMMARY", "DESCRIPTION"
}

/^BEGIN:VEVENT/{
    DTSTART=DTEND=LOCATION=SUMMARY=DESCRIPTION=""
}

$1~"^DTSTART.*"{DTSTART=$2}
$1~"^DTEND.*"{DTEND=$2}
$1=="LOCATION"{LOCATION=$2}
$1=="SUMMARY"{SUMMARY=substr($0,index($0,$2))}
$1=="DESCRIPTION"{DESCRIPTION=substr($0,index($0,$2))}

/^END:VEVENT/{
    print DTSTART,DTEND,
    "\""LOCATION"\"",
    "\""SUMMARY"\"",
    "\""DESCRIPTION"\""
}
