name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  download:
    name: Get data from horarius
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - shell: bash
        run: |
          sudo apt install dos2unix

      - shell: bash
        run: |
          ./getUrls.sh
        env:
          HORARIUS_KEY: ${{ secrets.HORARIUS_KEY }}

      - name: Upload website to artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: data

  save:
    name: save-change
    needs: download
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: data
          path: data

      - name: Commit files
        continue-on-error: true
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -f *
          echo "$(git diff --cached --stat -U1 --src-prefix=old/ --dst-prefix=new/)"
          git commit -m "Update $(date +%F) $(date +%R)" -m "$(git diff --cached --stat -U1 --src-prefix=old/ --dst-prefix=new/)"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} #To ensure main instead of master
