name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Download data from horarius:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - shell: bash
        run: |
          sudo apt install dos2unix

      - shell: bash
        run: |
          ./getUrls.sh
        env:
          HORARIUS_KEY: ${{ secrets.HORARIUS_KEY }}

      - name: Upload data-csv to artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-csv
          path: data/cal.csv

      - name: Upload artifact to page
        uses: actions/upload-pages-artifact@v3
        with:
          path: data/cal.ics

  save-changes-and-commit:
    needs: download
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download data-csv artifact
        uses: actions/download-artifact@v4
        with:
          name: data-csv
          path: data/cal.csv

      - name: Commit files
        continue-on-error: true
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -f *
          echo "$(git diff --cached --stat -U0 --src-prefix=old/ --dst-prefix=new/)"
          git commit -m "Update $(date +%F) $(date +%R)" -m "$(git diff --cached --stat -U0 --src-prefix=old/ --dst-prefix=new/)"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} #To ensure main instead of master

  deploy-to-page:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: Download data from horarius

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
